name: checks

on:
  workflow_call:
    inputs:
      lint_cs:
        type: boolean
        required: true

env:
  DOTNET_VERSION: '8.x'

jobs:
  lint_cs:
    runs-on: ubuntu-latest
    if: ${{ inputs.lint_cs }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Run linters
        run: dotnet format whitespace --folder --verify-no-changes Assets/Scripts