name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Run linters
        run: dotnet build
        run: dotnet format --check